# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bc70d745aec49abfe379cae6ff0fdfe8d9cf9e421ad34747a9c982eb0cceb282d0eb45df9a102d34d6c6ddd3b3b9b3ed2bce95fa4fa976bd34a2c182ed29f28

test:
  secret_key_base: 84d4437d4cb6544e8bc20e991883fdc198f2c95d77bccf0794ce4cfca364bf971facc28a304ef846107396d5837c8c632587668747115593c6b9cf82a141c79c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
